version: 0.2 

environment_variables:
  plaintext:
    DJANGO_SETTINGS_MODULE: 'ebdjango.settings'
    EnvType: 'test'

phases: 
  install: 
    runtime-versions: 
      python: 3.8
    commands: 
      # Install dependencies needed for running tests 
      - pip install -r requirements.txt
      # Logging directory doesn't exist by default when running test in container
      - mkdir -p '/opt/python/log'
 
  pre_build:
    commands:
      # Collect the static data
      - python manage.py collectstatic --noinput

  build: 
    commands: 
      # Discover and run unit tests. For more information, see <https://docs.djangoproject.com/en/2.0/topics/testing/overview/> 
      - python manage.py test --noinput