# Generated by Django 2.1.1 on 2020-01-27 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Training', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traininggroup',
            name='img',
        ),
    ]
