# Generated by Django 2.1.1 on 2020-01-28 19:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Training', '0002_remove_traininggroup_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingcourse',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
