# Generated by Django 2.1.1 on 2020-01-28 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Training', '0003_trainingcourse_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingcourse',
            name='link_href',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='trainingcourse',
            name='link_text',
            field=models.CharField(default='', max_length=10),
        ),
    ]
