# Generated by Django 2.1.1 on 2020-01-28 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Training', '0004_auto_20200128_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingcourse',
            name='short_text',
            field=models.CharField(default='', max_length=50),
        ),
    ]
