# Generated by Django 2.1.1 on 2020-02-04 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Training', '0005_trainingcourse_short_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingcourse',
            name='code_href',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='trainingcourse',
            name='code_text',
            field=models.CharField(default='', max_length=20),
        ),
    ]
