# Generated by Django 2.1.1 on 2020-02-05 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Training', '0006_auto_20200204_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingcourse',
            name='code_href',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='trainingcourse',
            name='code_text',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
