# Generated by Django 2.1.1 on 2020-03-08 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Training', '0009_trainingcourse_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='traininggroup',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
