# Generated by Django 2.1.1 on 2020-03-08 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Training', '0010_traininggroup_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='traininggroup',
            options={'ordering': ['id']},
        ),
    ]
