"""
Django settings for ebdjango project.

Generated by 'django-admin startproject' using Django 1.11.14.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os
from ebdjango.scripts import AWSParameterStore
from ebdjango.scripts import GeneralFunctions

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Get the Environment Type from the EC2 instance, codebuild, local pc etc.
# This is used to define database connections etc
AWS_ENV_TYPE = os.environ.get('EnvType', '')

# See if we have an environment variable named DOCKER, (length
# greater than 1), to see if we are connecting to docker db
DOCKER_PASSWORD = os.environ.get('DOCKER_PASSWORD', '')
DOCKER_USER = os.environ.get('DOCKER_USER', '')
DOCKER_DB = os.environ.get('DOCKER_DB', '')
DOCKER_HOST = os.environ.get('DOCKER_HOST', '')
DOCKER_PORT = os.environ.get('DOCKER_PORT', '')

# Setup AWS Parameter Store for database connections etc.
AWS_PSTORE_PROJECT = '/MarksWebsite/'
AWS_PSTORE_REGION = 'eu-west-2'
if AWS_ENV_TYPE == 'test' or AWS_ENV_TYPE == 'prod':
    AWSPStore = AWSParameterStore(AWS_PSTORE_PROJECT,
                                  AWS_ENV_TYPE,
                                  AWS_PSTORE_REGION)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
if len(AWS_ENV_TYPE) > 0:
    # Get SECRET KEY FROM Parameter Store.   AWS_ENV_TYPE should be
    # test or prod
    SECRET_KEY = AWSPStore.get_parameter('SecretKey', True)
else:
    # Use default SECRET_KEY for local computer
    SECRET_KEY = 'addlocalsecretkeyhere'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = bool(os.environ.get('DJANGO_DEBUG', False))

# GOOGLE recaptcha needs to use different keys if we are running a
# unit test (NOT THE 'test' AWS environment).   Define a variable for
# this with default False, but which is set to True within the tests
G_TESTING = False

# Get the recaptcha keys
if len(AWS_ENV_TYPE) > 0:
    # Get Recaptcha keys from parameter store
    G_RECAPTCHA_SITEKEY = AWSPStore.get_parameter('Recaptcha_SiteKey', False)
    G_RECAPTCHA_SECRETKEY = AWSPStore.get_parameter('Recaptcha_SecretKey',
                                                    True)
else:
    # (google recommends seperate localhost/127.0.0.1 keys)
    G_RECAPTCHA_SITEKEY = 'ADDGOOGLESITEKEYHERE'
    G_RECAPTCHA_SECRETKEY = 'ADDGOOGLESECRETKEYHERE'


ALLOWED_HOSTS = ['markswebsite-prod.eu-west-2.elasticbeanstalk.com',
                 'markswebsite-test.eu-west-2.elasticbeanstalk.com',
                 'test.markjohnwilson.net',
                 'markjohnwilson.net',
                 'www.markjohnwilson.net',
                 'localhost',
                 '127.0.0.1']

# Append EC2 IP to ALLOWED_HOSTS, necessary for health check to work.
GeneralFunctions.appendEC2IPToArray(ALLOWED_HOSTS)


# Application definition
INSTALLED_APPS = [
    'apps.AboutMe',
    'apps.ContactMe',
    'apps.Training',
    'apps.MyProjects',
    'apps.MySearch',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django.contrib.sitemaps',
]

SITE_ID = 1

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

'''
MIDDLEWARE_CLASSES = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
'''


ROOT_URLCONF = 'ebdjango.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['ebdjango/templates/'],      # MJW Update
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ebdjango.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

if len(AWS_ENV_TYPE) > 0:
    # Get SECRET KEY FROM Parameter Store.   AWS_ENV_TYPE should be
    # test or prod
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'dbMarksWebsite_'+AWS_ENV_TYPE,
            'USER': AWSPStore.get_parameter('DBUser', False),
            'PASSWORD': AWSPStore.get_parameter('DBPWD', True),
            'HOST': AWSPStore.get_parameter('DBHOST', False),
            'PORT': AWSPStore.get_parameter('DBPORT', False),
        }
    }
elif len(DOCKER_DB) > 0:
    # Connect to a docker database as specified in the docker-compose
    # file.
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': DOCKER_DB,
            'USER': DOCKER_USER,
            'PASSWORD': DOCKER_PASSWORD,
            'HOST': DOCKER_HOST,
            'PORT': DOCKER_PORT,
        }
    }
else:
    # Assume localc computer and connecting to localhost.
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'dbMarksWebsite',
            'USER': 'root',
            'PASSWORD': '2ttahbfa',
            'HOST': 'localhost',
            'PORT': '3306',
        }
    }

# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation'
                '.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation'
                '.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation'
                '.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation'
                '.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-gb'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = 'static'

STATICFILES_DIRS = [
    './ebdjango/static/',
]

# Please note that this generates index'd files within the static directory,
# however I don't really want to keeps a huge directory full of static files,
# so I have a tendancy to clean this directory out regulary.
STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.'\
                        'ManifestStaticFilesStorage'


# I spent considerable time looking at logging on aws.   Django tends to run
# as the user wsgi on linux.   There is also a group called wsgi, but they are
# not the same.   It is possible to create a log file in the /opt/python/log
# directory (wsgi group owns this) and then give ownership to the user wsgi.
# Then you have to worry about when the log file gets too big etc. If you
# write the lot out to the console, it will be collected within the
# /var/log/httpd/error_log which can easily be copied and filtered by
# [ebdjango]. AWS can then look after this file. I have a default LOG_LEVEL
# of ERROR and then change this to DEBUG in test and on my local computer.

# I DECIDED TO LOG TO THE CONSOLE WHEN IN test or prod AND TO A FILE WHEN
# RUNNING LOCALLY.

LOG_LEVEL = 'ERROR' if (AWS_ENV_TYPE == 'prod') else 'DEBUG'

if len(AWS_ENV_TYPE) > 0:

    # PROD/TEST Logging

    LOGGING = {
        'version': 1,
        'disable_existing_loggers': False,
        'formatters': {
            'ebdjangoFormat': {
                'format': "[%(asctime)s] [%(levelname)s] [ebdjango]"
                          " [%(pathname)s] [%(funcName)s] [%(lineno)d]"
                          " [%(message)s]"
                },
        },
        'handlers': {
            'console': {
                'level': LOG_LEVEL,
                'class': 'logging.StreamHandler',
                'formatter': 'ebdjangoFormat',
            },
        },
        'loggers': {
            'ebdjango': {
                'handlers': ['console'],
                'level': LOG_LEVEL,
                'propagate': True,
            },
        },
    }

else:

    # Logging for local machine in file ebdjango_logging.log
    # This also logs 'django' logs.

    LOGGING = {
        'version': 1,
        'disable_existing_loggers': False,
        'formatters': {
            'ebdjangoFormat': {
                'format': "[%(asctime)s] [%(levelname)s] [ebdjango]"
                          " [%(pathname)s] [%(funcName)s] [%(lineno)d]"
                          " [%(message)s]"
                },
        },
        'handlers': {
            'file': {
                'level': LOG_LEVEL,
                'class': 'logging.FileHandler',
                'filename': 'ebdjango_logging.log',
                'formatter': 'ebdjangoFormat',
            },
        },
        'loggers': {
            'django': {
                'handlers': ['file'],
                'level': LOG_LEVEL,
                'propagate': True,
            },
            'ebdjango': {
                'handlers': ['file'],
                'level': LOG_LEVEL,
                'propagate': True,
            },
        },
    }
