# Generated by Django 2.1.1 on 2020-01-27 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('img', models.CharField(max_length=50)),
                ('main_text', models.TextField(blank=True, default='main project description ...', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='languages',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyProjects.ProjectLanguage'),
        ),
    ]
