# Generated by Django 2.1.1 on 2020-01-27 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyProjects', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project',
            new_name='MyProject',
        ),
    ]
