# Generated by Django 2.1.1 on 2020-01-27 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyProjects', '0002_auto_20200127_2005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myproject',
            old_name='languages',
            new_name='language',
        ),
    ]
