# Generated by Django 2.1.1 on 2020-01-28 19:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyProjects', '0003_auto_20200127_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='myproject',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
