# Generated by Django 2.1.1 on 2020-02-04 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyProjects', '0006_myproject_short_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='myproject',
            name='code_href',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='myproject',
            name='code_text',
            field=models.CharField(default='', max_length=20),
        ),
    ]
