# Generated by Django 2.1.1 on 2020-02-05 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyProjects', '0007_auto_20200204_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myproject',
            name='link_href',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='myproject',
            name='link_text',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
