# Generated by Django 2.1.1 on 2020-03-08 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyProjects', '0008_auto_20200205_0913'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myproject',
            options={'ordering': ['-date', 'id']},
        ),
        migrations.AlterModelOptions(
            name='projectlanguage',
            options={'ordering': ['id']},
        ),
    ]
